config/routes.rb
Tagalong::Application.routes.draw do

  

  
  root 'index#index'
  resources :users
  resources :events
  resources :sessions, only: [:new, :create, :destroy]
  match '/register',  to: 'users#new',            via: 'get'
  match '/login',  to: 'sessions#new',         via: 'get'
  match '/logout', to: 'sessions#destroy',     via: 'delete'
  match '/get_nearby', to: 'users#get_nearby',    via: 'get'
  match '/get_user_coordinates', to: 'users#get_user_coordinates',    via: 'get'
end

app/models/events.rb
class Events < ActiveRecord::Base
  belongs_to :user
  acts_as_mappable
  
  validates :user_id, :presence => true
  validates :title, :presence => true
  validates :description, :presence => true
  validates :location, :presence => true
  validates :time, :presence => true
  validates :count_members, :presence => true
  validates :max_members, :presence => true

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :events
  attr_accessor :ip_address, :lat, :lon
  
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  
  EMAIL_REGEX = /\A[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\z/i
  validates :firstname, :presence => true
  validates :lastname, :presence => true
  validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
  validates :email, :presence => true, :uniqueness => { case_sensitive: false }, :format => EMAIL_REGEX
  validates :password, :confirmation => true #password_confirmation attr
  has_secure_password
  validates_length_of :password, :in => 6..20, :on => :create
  
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end
  
  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end
     
  private
  
    def create_remember_token
      self.remember_token = User.hash(User.new_remember_token)
    end
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Events.all
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    if User.exists?(username: user_params[:username_or_email])
      @user = User.find_by(username: user_params[:username_or_email])
    elsif User.exists?(username: user_params[:username_or_email])
      @user = User.find_by(email: user_params[:username_or_email])
    end

    if @user && @user.authenticate(user_params[:password])
      sign_in @user, request.remote_ip
      redirect_to @user
    elsif @user
      flash.now[:error] = 'Invalid email/password combination'
      redirect_to root_url
    else
      flash.now[:error] = "No account found. Please re-enter your credentials or register a new account"
      redirect_to root_url
    end
  end
  
  def destroy
    sign_out
    redirect_to root_url
  end
  
  def update_user_position
    update_position position_params[:position]
    respond_to do |format|
      format.html { redirect_to(current_user) }
      format.json { render :text => "User location updated" }
    end

  end
    
  private
  def user_params
    params.require(:session).permit(:username_or_email, :password)
  end
  
  def position_params
    params.require(:session).permit(:position)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new 
  end
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:error] = "You signed up successfully"
      redirect_to root_url
      #redirect_to user_path(@user)
    else
      flash[:error] = "Form is invalid"
      redirect_to root_url
      #render "new"
    end
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def get_user_coordinates
    current_user.ip_address = request.ip
    current_user.lat = Geocoder.coordinates(current_user.ip_address)[0]
    puts YAML::dump(current_user)
    
    respond_to do |format|
    #  format.html { redirect_to(current_user) }
      format.json { render json: current_user }
    end
    
  end
  
  private
  def user_params
    params.require(:user).permit(:firstname, :lastname, :username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def sign_in(user, ip)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    session[:user_id] = user.id
    user.update_attribute(:remember_token, User.hash(remember_token))
    self.current_user = user
    
  end
  
  def update_position(position)
    session[:user] = JSON.parse(position)
  end
    
  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.hash(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    remember_token = User.hash(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
  def get_coordinates
    current_user.ip_address = Geocoder.request.ip
    current_user.location = Geocoder.coordinates(current_user.ip_address)
    
  end
  
end

app/views/events/index.html.erb
<ul>
<% @events.each do |event| %>
  <li><%= event %></li>
 <% end %>
</ul>

app/views/events/new.html.erb
<%= form_for(:event, :url => {:controller => 'events', :action => 'create'}) do |f| %>
  <table>
    <tr>
      <td>
        <%= f.text_area :description, :placeholder_text => "Enter a short event description here", size: "8x8", :maxlength => 140 %>
      </td>
    </tr>

    <tr>
      <td>
      <%= f.submit :Register %>
      </td>
    </tr>  
  </table>
<% end %>

app/views/index/index.html.erb
<h1>Welcome to Tagalong</h1>
<%= link_to 'Login', login_path %>
<%= form_for(:session, url: sessions_path, :html => {:id => "login_form"}) do |f| %>
<table>
  <tr>
    <td>
      <%= f.text_field :firstname, :placeholder => 'First name', :class => "user_form" %>
    </td>
  </tr>
  <tr>
    <td>
      <%= f.text_field :lastname, :placeholder => 'Last name', :class => "user_form" %>
    </td>
  </tr>   
  <tr>
    <td>
      <%= f.text_field :username_or_email, :placeholder => 'Username or Email', :class => "session_form" %>
    </td>
  </tr>
  <tr>
    <td>
      <%= f.text_field :email, :placeholder => 'Email', :class => "user_form" %>
    </td>
  </tr>  
  <tr>
    <td>
      <%= f.password_field :password, :placeholder => 'Password', :class => "session_form" %>
    </td>
  </tr>
  <tr>      
    <td>
      <%= f.password_field :password_confirmation, :placeholder => 'Confirm password', :class => "user_form" %>
    </td>
  </tr>
  <tr>
    <td>
      <%= f.submit :Login %>
    </td>
  </tr>
</table>
<% end %>
<%= content_tag 'a', 'Register', :id => "reg_link" %>
<br>
<%= link_to 'Browse Events', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tagalong</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
</body>
</html>

app/views/users/index.html.erb
<h2>Create new user:</h2>
<% if flash[:notice] %>
<h3><%= flash[:notice] %></h3>
<% end %>
<%= form_for :user, url: users_path do |f| %>
  <table>
    <tr>
      <td>
        <%= f.text_field :first, :placeholder => "First name" %>
      </td>
    </tr>
    <tr>    
      <td>
        <%= f.text_field :last, :placeholder => "Last name" %> 
      </td>
    </tr>
    <tr>
      <td>
        <%= f.text_field :username, :placeholder => "Username" %> 
      </td>
    </tr>
    <tr>    
      <td>  
      <%= f.text_field :email, :placeholder => "Email address" %> 
      </td>
    </tr>
    <tr>    
      <td>
        <%= f.password_field :password, :placeholder => "Password" %>
      </td>
    </tr>
    <tr>    
      <td>
        <%= f.password_field :password2, :placeholder => "Re-type password" %>      
      </td>
    </tr>
    <tr>
      <td>
        <%= f.submit %>
      </td>
    </tr>
  </table>
<% end %>
<h2>Sign In</h2>
<%= form_for :user, url: users_path do |f| %>
  <table>
    <tr>
      <td>
        <%= f.text_field :username, :placeholder => "Username" %> 
      </td>
    </tr>
    <tr>    
      <td>
        <%= f.password_field :password, :placeholder => "Password" %>
      </td>
    </tr>
    <tr>
      <td>
        <%= f.submit %>
      </td>
    </tr>
  </table>
<% end %>

app/views/users/new.html.erb
<% if @user.errors.any? %>
    <ul class="Signup_Errors">
    <% for message_error in @user.errors.full_messages %>
      <li><%= message_error %></li>
    <% end %>
    </ul>
 <% end %>
<%= form_for(@user) do |f| %>
  <table>
    <tr>
      <td>
        <%= f.text_field :firstname, :placeholder => 'First name' %>
      </td>
    </tr>
    <tr>
      <td>
        <%= f.text_field :lastname, :placeholder => 'Last name' %>
      </td>
    </tr>
    <tr>
      <td>
        <%= f.text_field :username, :placeholder => 'Username' %>
      </td>
    </tr>
    <tr>
      <td>
        <%= f.text_field :email, :placeholder => 'Email' %>
      </td>
    </tr>
    <tr>      
      <td>
        <%= f.password_field :password, :placeholder => 'Password' %>
      </td>
    </tr>
    <tr>      
      <td>
        <%= f.password_field :password_confirmation, :placeholder => 'Confirm password' %>
      </td>
    </tr>
    <tr>
      <td>
      <%= f.submit :Register %>
      </td>
    </tr>  
  </table>
<% end %>

app/views/users/show.html.erb
<nav>
<%if signed_in? %>
  <%= link_to "My Profile", current_user %>
  <%= link_to "My Events", "#" %>
  <%= link_to "Settings", "#" %>
  <%= link_to "Sign Out", logout_path, method: "delete" %>
<% else %>
  <%= link_to login_path %>
<% end %>
</nav>
<h2>Hey <%= @user.firstname %>!</h2>
<table>
	<tr>
		<td>
			<h2>Your events</h2>
		</td>
		<td>
			<h2>Nearby events</h2>
		</td>
	</tr>
	<tr>
		<td>
			<h3 id="new_event">Create a new event</h3>
			<div id="new_event_form">
				<%= form_for :event, url: sessions_path, remote: true do |f| %>
				<table>
					<tr>
						<td>
							<%= f.text_area :description, :placeholder => "Describe the event", maxlength: 140, size: "40x5", :id => "description" %>
						</td>
						<td>
							<input disabled maxlength="3" size="3" value="140" id="charCounter"> Characters Left</input>
						</td>
					</tr>
					<tr>
						<td>	
							<%= f.text_field :location, :placeholder => "Start typing your location", size: "40" %>
						</td>
					</tr>
					<tr>
						<td>
							<% options = [['Tag-a-longs?', 0], ['1', 1], ['2', 2], ['3', 3], ['4', 4], ['5', 5], ['6', 6], ['7', 7], ['8', 8], ['9', 9], ['10+', 10]] %>
							<%= f.select :email_provider, options_for_select(options, 0) %>
						</td>
					</tr>
					<tr>
						<td>
							<%= f.hidden_field :creator, :value => @user.id %>
							<%= f.submit "Create Event!" %>
						</td>
					</tr>
				</table>
				<% end %>
			</div>
			<ul>
				<li>test</li>
				<li>test</li>
				<li>test</li>
			</ul>
		</td>
		<td>
		</td>
	</tr>
</table>